<div class="overflow-x-auto">
    <table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-white/10">
        <thead class="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500 dark:bg-[#07131f] dark:text-slate-400">
            <tr>
                <th class="px-4 py-3">Report</th>
                <th class="px-4 py-3">Generated By</th>
                <th class="px-4 py-3">Date Range</th>
                <th class="px-4 py-3">Status</th>
                <th class="px-4 py-3">Download</th>
            </tr>
        </thead>
        <tbody class="divide-y divide-slate-200 dark:divide-white/10">
            @forelse($reports as $report)
                <tr class="hover:bg-slate-50 dark:hover:bg-white/5">
                    <td class="px-4 py-4">
                        <div class="font-semibold text-slate-900 dark:text-white">{{ $report->title }}</div>
                        <div class="mt-1 text-xs text-slate-500 dark:text-slate-400">
                            {{ ucfirst($report->report_type) }}{{ $report->client ? ' / '.$report->client->name : '' }}{{ $report->application ? ' / '.$report->application->name : '' }}
                        </div>
                    </td>
                    <td class="px-4 py-4 text-slate-600 dark:text-slate-300">{{ $report->generatedBy?->name ?? 'System' }}</td>
                    <td class="px-4 py-4 text-slate-600 dark:text-slate-300">{{ $report->period_start->format('Y-m-d') }} to {{ $report->period_end->format('Y-m-d') }}</td>
                    <td class="px-4 py-4">
                        @php
                            $statusClass = match ($report->status) {
                                'completed' => 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-200',
                                'failed' => 'bg-red-100 text-red-700 dark:bg-red-500/20 dark:text-red-200',
                                'processing' => 'bg-blue-100 text-blue-700 dark:bg-blue-500/20 dark:text-blue-200',
                                default => 'bg-amber-100 text-amber-700 dark:bg-amber-500/20 dark:text-amber-200',
                            };
                        @endphp
                        <span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold {{ $statusClass }}">{{ ucfirst($report->status) }}</span>
                        @if($report->status === 'failed' && $report->error_message)
                            <div class="mt-1 max-w-xs truncate text-xs text-red-600 dark:text-red-300">{{ $report->error_message }}</div>
                        @endif
                    </td>
                    <td class="px-4 py-4">
                        @if($report->status === 'completed' && $report->file_path)
                            @can('module.reports.download')
                                <a href="{{ route('reports.maintenance.download', $report) }}" class="inline-flex items-center justify-center rounded-lg bg-orange-600 px-3 py-2 text-xs font-semibold text-white hover:bg-orange-500">Download</a>
                            @else
                                <span class="text-xs text-slate-500 dark:text-slate-400">No permission</span>
                            @endcan
                        @elseif(in_array($report->status, ['pending', 'processing'], true))
                            <span class="text-xs text-slate-500 dark:text-slate-400">Preparing</span>
                        @else
                            <span class="text-xs text-slate-500 dark:text-slate-400">HTML preview</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="px-4 py-12 text-center text-slate-500 dark:text-slate-400">No maintenance reports generated yet.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</div>
