@php
    $pdf = $pdf ?? false;
    $executive = $summary['executive'] ?? [];
    $scope = $summary['scope'] ?? [];
@endphp

<div class="{{ $pdf ? 'cover' : 'rounded-2xl bg-slate-50 p-6 dark:bg-slate-950/60' }}">
    <div class="{{ $pdf ? '' : 'text-sm font-bold uppercase tracking-widest text-orange-600 dark:text-orange-300' }}">Enterprise Maintenance Report</div>
    <h1 class="{{ $pdf ? '' : 'mt-3 text-3xl font-bold text-slate-950 dark:text-white' }}">{{ $report->title }}</h1>
    <p class="{{ $pdf ? 'muted' : 'mt-2 text-sm text-slate-500 dark:text-slate-400' }}">
        Period: {{ $report->period_start->format('Y-m-d H:i') }} to {{ $report->period_end->format('Y-m-d H:i') }}
        <br>Generated by: {{ $report->generatedBy?->name ?? 'System' }} on {{ $report->created_at->format('Y-m-d H:i') }}
    </p>
    <p class="{{ $pdf ? 'pill' : 'mt-5 inline-flex rounded-full bg-orange-100 px-3 py-1 text-sm font-bold text-orange-700 dark:bg-orange-500/20 dark:text-orange-200' }}">
        Overall status: {{ ucfirst($executive['overall_status'] ?? 'unknown') }}
    </p>
</div>

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Executive Summary</h2>
<p class="{{ $pdf ? '' : 'mt-2 text-sm text-slate-600 dark:text-slate-300' }}">{{ $executive['headline'] ?? 'No summary available.' }}</p>
<div class="{{ $pdf ? '' : 'mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5' }}">
    @foreach(($executive['key_metrics'] ?? []) as $label => $value)
        <div class="{{ $pdf ? 'metric' : 'rounded-xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-slate-950/60' }}">
            <div class="{{ $pdf ? 'muted' : 'text-xs font-bold uppercase tracking-widest text-slate-500' }}">{{ $label }}</div>
            <strong class="{{ $pdf ? '' : 'mt-2 block text-lg text-slate-950 dark:text-white' }}">{{ $value }}</strong>
        </div>
    @endforeach
</div>

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Scope</h2>
<table class="{{ $pdf ? '' : 'mt-3 min-w-full divide-y divide-slate-200 text-sm dark:divide-white/10' }}">
    <tbody>
        <tr><th>Report Type</th><td>{{ ucfirst($scope['report_type'] ?? $report->report_type) }}</td></tr>
        <tr><th>Application Filter</th><td>{{ $scope['application']['name'] ?? 'All applications' }}</td></tr>
        <tr><th>Environment</th><td>{{ $scope['environment'] ?: 'All environments' }}</td></tr>
        <tr><th>Server Group</th><td>{{ $scope['server_group'] ?: 'All groups' }}</td></tr>
        <tr><th>Assets Covered</th><td>{{ $scope['application_count'] ?? 0 }} applications, {{ $scope['server_count'] ?? 0 }} servers, {{ $scope['monitor_count'] ?? 0 }} website monitors</td></tr>
    </tbody>
</table>

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Availability / SLA</h2>
<p class="{{ $pdf ? '' : 'text-sm text-slate-600 dark:text-slate-300' }}">
    Average website uptime: {{ $summary['website']['average_uptime'] === null ? 'No data' : $summary['website']['average_uptime'].'%' }}.
    Downtime checks recorded: {{ $summary['website']['downtime_count'] ?? 0 }}.
</p>
@include('reports.maintenance.table', ['headers' => ['Monitor', 'URL', 'Checks', 'Downtime', 'Uptime'], 'rows' => collect($summary['website']['rows'] ?? [])->map(fn ($row) => [$row['name'], $row['url'], $row['checks'], $row['downtime_count'], $row['uptime_percent'] === null ? 'No data' : $row['uptime_percent'].'%'])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Infrastructure Health</h2>
<p class="{{ $pdf ? '' : 'text-sm text-slate-600 dark:text-slate-300' }}">
    Online: {{ $summary['servers']['online'] ?? 0 }}. Offline: {{ $summary['servers']['offline'] ?? 0 }}. Unknown: {{ $summary['servers']['unknown'] ?? 0 }}.
</p>
@include('reports.maintenance.table', ['headers' => ['Server', 'Group', 'Heartbeat', 'CPU Avg/Max', 'RAM Avg/Max', 'Disk Avg/Max'], 'rows' => collect($summary['servers']['rows'] ?? [])->map(fn ($row) => [$row['name'], $row['group'] ?: '-', $row['heartbeat'], ($row['cpu_avg'] ?? '-').'/'.($row['cpu_max'] ?? '-'), ($row['ram_avg'] ?? '-').'/'.($row['ram_max'] ?? '-'), ($row['disk_avg'] ?? '-').'/'.($row['disk_max'] ?? '-')])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Application Health</h2>
@include('reports.maintenance.table', ['headers' => ['Application', 'Environment', 'Health', 'URL', 'App Servers', 'DB Servers'], 'rows' => collect($summary['applications'] ?? [])->map(fn ($row) => [$row['name'], $row['environment'] ?: '-', $row['status'], $row['url_status'], $row['app_servers']['healthy'].'/'.$row['app_servers']['total'], $row['database_servers']['healthy'].'/'.$row['database_servers']['total']])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Database Health</h2>
<p class="{{ $pdf ? '' : 'text-sm text-slate-600 dark:text-slate-300' }}">Checks: {{ $summary['database']['checks'] ?? 0 }}. Success: {{ $summary['database']['success'] ?? 0 }}. Failures: {{ $summary['database']['failures'] ?? 0 }}.</p>
@include('reports.maintenance.table', ['headers' => ['Name', 'Driver', 'Host', 'Last Status', 'Last Checked'], 'rows' => collect($summary['database']['rows'] ?? [])->map(fn ($row) => [$row['name'], $row['driver'], $row['host'], $row['last_status'], $row['last_checked_at'] ?: '-'])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Network Connectivity Summary</h2>
<p class="{{ $pdf ? '' : 'text-sm text-slate-600 dark:text-slate-300' }}">
    Checks: {{ $summary['network']['checks'] ?? 0 }}.
    Success: {{ $summary['network']['success'] ?? 0 }}.
    Failures: {{ $summary['network']['failures'] ?? 0 }}.
    Affected applications: {{ empty($summary['network']['affected_applications'] ?? []) ? 'None' : implode(', ', $summary['network']['affected_applications']) }}.
</p>
@include('reports.maintenance.table', ['headers' => ['Name', 'Dependency', 'Source', 'Destination', 'Port/Protocol', 'Last Status', 'Application'], 'rows' => collect($summary['network']['rows'] ?? [])->map(fn ($row) => [$row['name'], $row['dependency_type'], $row['source'], $row['destination'], ($row['port'] ?: '-').'/'.$row['protocol'], $row['last_status'], $row['application'] ?: '-'])->all(), 'pdf' => $pdf])
<h3 class="{{ $pdf ? '' : 'mt-4 text-sm font-bold text-slate-900 dark:text-white' }}">Failed Dependencies</h3>
@include('reports.maintenance.table', ['headers' => ['Name', 'Target', 'Status', 'Affected Application', 'Error'], 'rows' => collect($summary['network']['failed_rows'] ?? [])->map(fn ($row) => [$row['name'], $row['target'], $row['status'], $row['affected_application'] ?: '-', $row['error'] ?: '-'])->all(), 'pdf' => $pdf])
<h3 class="{{ $pdf ? '' : 'mt-4 text-sm font-bold text-slate-900 dark:text-white' }}">DNS Mismatch / Drift</h3>
@include('reports.maintenance.table', ['headers' => ['Name', 'Host', 'Expected', 'Resolved', 'Status', 'Application'], 'rows' => collect($summary['network']['dns_mismatches'] ?? [])->map(fn ($row) => [$row['name'], $row['host'], $row['expected'] ?: '-', $row['resolved'] ?: '-', $row['status'], $row['affected_application'] ?: '-'])->all(), 'pdf' => $pdf])
<h3 class="{{ $pdf ? '' : 'mt-4 text-sm font-bold text-slate-900 dark:text-white' }}">Port Baseline Violations</h3>
@include('reports.maintenance.table', ['headers' => ['Server', 'Port', 'Expected', 'Last Status', 'Error'], 'rows' => collect($summary['network']['port_baseline_violations'] ?? [])->map(fn ($row) => [$row['server'], $row['port'].'/'.$row['protocol'], $row['expected_state'], $row['last_status'], $row['last_error'] ?: '-'])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">IIS Log Summary</h2>
<p class="{{ $pdf ? '' : 'text-sm text-slate-600 dark:text-slate-300' }}">
    Requests: {{ number_format((int) ($summary['iis']['total_requests'] ?? 0)) }}.
    404: {{ number_format((int) ($summary['iis']['http_404'] ?? 0)) }}.
    500: {{ number_format((int) ($summary['iis']['http_500'] ?? 0)) }}.
    Suspicious: {{ number_format((int) ($summary['iis']['suspicious_count'] ?? 0)) }}.
</p>
<h3 class="{{ $pdf ? '' : 'mt-4 text-sm font-bold text-slate-900 dark:text-white' }}">Top IPs</h3>
@include('reports.maintenance.table', ['headers' => ['IP', 'Count'], 'rows' => collect($summary['iis']['top_ips'] ?? [])->map(fn ($row) => [$row['value'], $row['count']])->all(), 'pdf' => $pdf])
<h3 class="{{ $pdf ? '' : 'mt-4 text-sm font-bold text-slate-900 dark:text-white' }}">Top URLs</h3>
@include('reports.maintenance.table', ['headers' => ['URL', 'Count'], 'rows' => collect($summary['iis']['top_urls'] ?? [])->map(fn ($row) => [$row['value'], $row['count']])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">SSL Certificate Status</h2>
@include('reports.maintenance.table', ['headers' => ['Monitor', 'URL', 'Expires', 'Days Left', 'Status'], 'rows' => collect($summary['ssl']['rows'] ?? [])->map(fn ($row) => [$row['name'], $row['url'], $row['expires_at'] ?: '-', $row['days_left'] ?? '-', $row['status']])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Incidents and Alerts</h2>
@include('reports.maintenance.table', ['headers' => ['Type', 'Severity', 'Count'], 'rows' => collect($summary['incidents']['rows'] ?? [])->map(fn ($row) => [$row['type'], $row['severity'], $row['count']])->all(), 'pdf' => $pdf])

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Recommendations</h2>
<ol class="{{ $pdf ? '' : 'mt-3 list-decimal space-y-2 pl-5 text-sm text-slate-700 dark:text-slate-200' }}">
    @foreach(($summary['recommendations'] ?? []) as $recommendation)
        <li>{{ $recommendation }}</li>
    @endforeach
</ol>

<h2 class="{{ $pdf ? '' : 'mt-8 text-xl font-bold text-slate-900 dark:text-white' }}">Appendix</h2>
<p class="{{ $pdf ? 'muted' : 'text-sm text-slate-500 dark:text-slate-400' }}">Security scans: {{ $summary['security']['webshell_scans'] ?? 0 }} webshell scans, {{ $summary['security']['webshell_findings'] ?? 0 }} webshell findings, {{ $summary['security']['seo_scans'] ?? 0 }} SEO scans, {{ $summary['security']['seo_suspicious'] ?? 0 }} suspicious SEO results.</p>
